# Generated by Django 4.0 on 2021-12-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatoritem',
            name='language',
            field=models.TextField(default=' '),
        ),
    ]
