# Generated by Django 4.0 on 2021-12-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0002_translatoritem_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatoritem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='translatoritem',
            name='translated_data',
        ),
    ]
