# Generated by Django 4.0 on 2021-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0003_remove_translatoritem_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatoritem',
            name='language',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='translatoritem',
            name='translated_data',
            field=models.TextField(default=' '),
        ),
    ]
